services:
  app:
    build: .
    container_name: zendo-python-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload --reload-include *
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}


  
  postgres:
    image: postgres
    container_name: zendo-python-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3bkr@2251998
      - POSTGRES_DB=ZenDoDB
    ports:
        - 5432:5432
